package project.model;

/**
 * BaseEntity is an abstract parent class for all persistent model objects.
 *
 * <p>This class demonstrates:
 * <ul>
 *   <li>Inheritance (Bookmark, HistoryEntry extend this class)</li>
 *   <li>Encapsulation through private fields and public getters/setters</li>
 *   <li>OOP design by defining a common identity attribute</li>
 * </ul>
 */
public abstract class BaseEntity {

    /** Primary key (auto-generated by the database). */
    private int id;

    /**
     * Default constructor required for frameworks and DAO hydration.
     */
    public BaseEntity() {
    }

    /**
     * Constructor used when an entity is retrieved from the database.
     *
     * @param id the unique identifier assigned by the database
     */
    public BaseEntity(int id) {
        this.id = id;
    }

    /** Returns the numeric database primary key. */
    public int getId() {
        return id;
    }

    /** Sets the primary key value (used after database insertion). */
    public void setId(int id) {
        this.id = id;
    }
}
